"""initial schema

Revision ID: 3dffc1e2279e
Revises: 
Create Date: 2026-06-27 17:02:50.421870

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3dffc1e2279e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Enum string: admin | attorney | intake_coordinator | readonly. Immutable after create.'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('is_default_assignee', sa.Boolean(), server_default='false', nullable=False, comment='At most one true row among role=attorney (F6.1).'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('lead_intake_pending',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Lowercase + trim normalized (D7).'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('temp_resume_storage_key', sa.String(length=500), nullable=False, comment='Pending file location until L1b promotes it to resume_files.'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Hash of single-use verification token; never store the raw token.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Set when L1b succeeds; prevents replay.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_lead_intake_pending_email'), 'lead_intake_pending', ['email'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Lowercase + trim normalized (D7). Unique match key on submit.'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=True)
    op.create_table('resume_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='Relative path or S3 key, e.g. uploads/{uuid}.pdf. Never expose to client.'),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Snapshot at submit (denormalized from form).'),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Snapshot at submit (denormalized; lowercase per D7).'),
    sa.Column('resume_file_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=50), server_default='PENDING', nullable=False, comment='Enum: PENDING | REACHED_OUT | QUALIFIED | DISQUALIFIED | CLOSED.'),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Set on create and on every state change (replaces IN_CONTACT/ON_HOLD).'),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM-extracted; null until enriched (F7.1).'),
    sa.Column('assigned_account_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (L14). Null = active.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_account_id'), 'leads', ['assigned_account_id'], unique=False)
    op.create_index(op.f('ix_leads_prospect_id'), 'leads', ['prospect_id'], unique=False)
    op.create_table('email_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Groups emails in one (lead_id, recipient) thread.'),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False, comment='Template key, e.g. prospect_confirmation, attorney_new_lead, email_verification.'),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Enum: pending | sent | failed.'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_notifications_conversation_id_created_at', 'email_notifications', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_email_notifications_lead_id'), 'email_notifications', ['lead_id'], unique=False)
    op.create_table('lead_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True, comment='Null on initial create.'),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('changed_by_account_id', sa.UUID(), nullable=True, comment='Null when system inserted the initial row.'),
    sa.Column('note', sa.Text(), nullable=True, comment='Optional reason captured on L10 transitions.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_state_history_lead_id'), 'lead_state_history', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_state_history_lead_id'), table_name='lead_state_history')
    op.drop_table('lead_state_history')
    op.drop_index(op.f('ix_email_notifications_lead_id'), table_name='email_notifications')
    op.drop_index('ix_email_notifications_conversation_id_created_at', table_name='email_notifications')
    op.drop_table('email_notifications')
    op.drop_index(op.f('ix_leads_prospect_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('resume_files')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_lead_intake_pending_email'), table_name='lead_intake_pending')
    op.drop_table('lead_intake_pending')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
